trigger:
  branches:
    include:
      - main  # Replace 'main' with your default branch name if different

pool:
  vmImage: 'ubuntu-latest'  # You can choose a different image if needed

steps:
  - script: |
      pip install pytest
      pytest class_test.py
    displayName: 'Run pytest'
    continueOnError: false